"""
Report Writer Agent
────────────────────
Composes the final Markdown intelligence report from all prior agent outputs.
Saves it to the /reports directory with a date-stamped filename.
"""

import os
from datetime import datetime
from pathlib import Path

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, SystemMessage

import config
from graph.state import PipelineState, AnalyzedArticle, InsightsOutput


llm = ChatGoogleGenerativeAI(
    model=config.GEMINI_MODEL,
    google_api_key=config.GEMINI_API_KEY,
    temperature=0.4,
)

WRITER_SYSTEM_PROMPT = """You are a professional technology intelligence analyst writing a
daily AI news briefing for a senior audience. Write in a crisp, authoritative style.
Do not use bullet points for everything — mix in short paragraphs where appropriate.
The report should feel like a premium intelligence product, not a listicle.
"""


def sentiment_emoji(sentiment) -> str:
    val = sentiment.value if hasattr(sentiment, "value") else sentiment
    return {"positive": "🟢", "neutral": "🔵", "negative": "🔴"}.get(val, "⚪")


def importance_bar(score: float) -> str:
    filled = round(score * 5)
    return "█" * filled + "░" * (5 - filled)


def build_articles_section(articles: list[AnalyzedArticle]) -> str:
    """Build the 'Top Stories' section, sorted by importance score."""
    sorted_articles = sorted(articles, key=lambda a: a.importance_score, reverse=True)
    lines = ["## 📰 Top Stories\n"]

    for i, a in enumerate(sorted_articles[:15], 1):  # top 15
        lines.append(
            f"### {i}. {a.title}\n"
            f"**Source:** {a.source} &nbsp;|&nbsp; "
            f"**Date:** {a.date} &nbsp;|&nbsp; "
            f"**Importance:** {importance_bar(a.importance_score)} ({a.importance_score:.2f}) | ; "
            f"{sentiment_emoji(a.sentiment)} {a.sentiment.capitalize()}\n\n"
            f"{a.summary}\n\n"
            f"**Topics:** {', '.join(f'`{t}`' for t in a.topics)}\n\n"
            f"**Entities:** {', '.join(a.entities)}\n\n"
            f"🔗 [{a.url}]({a.url})\n\n---\n"
        )
    return "\n".join(lines)


def build_signals_section(insights: InsightsOutput) -> str:
    lines = ["## 🔭 Signals\n"]
    if insights.emerging_topics:
        lines.append("### 🌱 Emerging Topics\n")
        lines.append(", ".join(f"`{t}`" for t in insights.emerging_topics) + "\n")
    if insights.key_entities_today:
        lines.append("\n### 🏢 Key Players Today\n")
        lines.append(", ".join(f"**{e}**" for e in insights.key_entities_today) + "\n")
    return "\n".join(lines)


# Report Writer LangGraph Node 

async def report_writer_node(state: PipelineState) -> PipelineState:
    print(f"\n [Report Writer] Composing final report...")

    insights = state["insights"]
    articles = state["analyzed_articles"]
    run_date = state["run_date"]
    today_fmt = datetime.fromisoformat(run_date).strftime("%B %d, %Y")

    # Build report sections
    header = (
        f"# 🤖 AI News Intelligence Report\n"
        f"**Date:** {today_fmt}  \n"
        f"**Articles analyzed:** {len(articles)}  \n"
        f"**Query:** {state['query']}\n\n"
        f"---\n"
    )

    exec_summary = ""
    if insights and insights.executive_summary:
        exec_summary = (
            f"## 🎯 Executive Summary\n\n"
            f"{insights.executive_summary}\n\n"
            f"---\n"
        )

    todays_themes = ""
    if insights and insights.todays_themes:
        todays_themes = (
            f"## 🏷️ Today's Core Themes\n\n"
            + " | ".join(f"`{t}`" for t in insights.todays_themes)
            + "\n\n---\n"
        )

    articles_section = build_articles_section(articles)
    signals_section = build_signals_section(insights) if insights else ""

    footer = (
        f"\n---\n"
        f"*Report generated by AI News Intelligence Agent on {today_fmt}. "
        f"Powered by Gemini {config.GEMINI_MODEL} + LangGraph.*\n"
    )

    full_report = "\n\n".join(filter(bool, [
        header,
        exec_summary,
        todays_themes,
        articles_section,
        signals_section,
        footer,
    ]))

    # Save report to file
    Path(config.REPORTS_DIR).mkdir(parents=True, exist_ok=True)
    filename = f"ai_news_{run_date}.md"
    report_path = os.path.join(config.REPORTS_DIR, filename)

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(full_report)

    state["report_markdown"] = full_report
    state["report_path"] = report_path

    print(f"   ✅ Report written: {report_path} ({len(full_report):,} chars)")
    return state
